---
development:
  cloud_name: peshy
  api_key: '661242298738243'
  api_secret: O5TA03GpGJgJ36XqO4vN-GQy9pA
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: peshy
  api_key: '661242298738243'
  api_secret: O5TA03GpGJgJ36XqO4vN-GQy9pA
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: peshy
  api_key: '661242298738243'
  api_secret: O5TA03GpGJgJ36XqO4vN-GQy9pA
  enhance_image_tag: true
  static_file_support: false
